In [24]:
import numpy as np

In [25]:
arr = np.array([[1,2,3], [4,5,6]])
print(np.ndim(arr))
print(np.shape(arr))

2
(2, 3)


In [26]:
np.reshape(arr,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr.sum()

21

In [28]:
arr.sum(axis=0)

array([5, 7, 9])

In [29]:
print(np.mean(arr))

3.5


In [30]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [41]:
# Crete a function that will allow you to create an array with 2n  rows and three columns find dimension shape, reshape in to opposite


def nparrays(rows, column):
    
    a = np.array([[2]*column]*rows)
    # for i in range(rows):
    #     for j in range(column):
    #         a[i][j] = int(input())
    print(a)
    print(np.shape(a))
    print(np.ndim(a))
    print(np.mean(a))
    print(np.reshape(a,[column,rows]))

nparrays(4,5)



[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
(4, 5)
2
2.0
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [43]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.random.rand((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer