In [24]:
import numpy as np

In [25]:
arr = np.array([[1,2,3], [4,5,6]])
print(np.ndim(arr))
print(np.shape(arr))

2
(2, 3)


In [26]:
np.reshape(arr,[3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr.sum()

21

In [28]:
arr.sum(axis=0)

array([5, 7, 9])

In [29]:
print(np.mean(arr))

3.5


In [30]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [41]:
# Crete a function that will allow you to create an array with 2n  rows and three columns find dimension shape, reshape in to opposite


def nparrays(rows, column):
    
    a = np.array([[2]*column]*rows)
    # for i in range(rows):
    #     for j in range(column):
    #         a[i][j] = int(input())
    print(a)
    print(np.shape(a))
    print(np.ndim(a))
    print(np.mean(a))
    print(np.reshape(a,[column,rows]))

nparrays(4,5)



[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
(4, 5)
2
2.0
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [43]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.random.randint(100)

53

In [52]:
ds_temp = np.random.randint(0,50, size=(365,5))
ds_temp
# np.shape(ds_temp)

array([[45, 43, 23, 33, 42],
       [ 0, 40, 14, 42, 32],
       [27, 40,  0, 33, 24],
       ...,
       [36, 11,  0, 40, 44],
       [28, 31, 30,  4, 46],
       [49, 31, 35, 36,  7]])

In [57]:
# basic statistic

mean_of_cities = np.mean(ds_temp, axis = 0)
print(mean_of_cities)

lowests = np.min(ds_temp, axis = 0)
print(lowests)


[25.12328767 24.21917808 24.09041096 24.13972603 25.02191781]
[0 0 0 0 0]


You have a NumPy array temperature_data of shape (365, 5) where each row represents a day of the year and each column represents a different city. The cities in order are New York, Los Angeles, Chicago, Houston, and Phoenix.
Tasks:
1.	Basic Statistics:
○	Calculate the mean temperature for each city over the entire year.
○	Find the maximum and minimum temperatures recorded for each city.
2.	Temperature Variability:
○	Compute the standard deviation of temperatures for each city.
○	Identify the day with the highest temperature variability (i.e., the day with the highest difference between the maximum and minimum temperatures across all cities).
3.	City-Specific Analysis:
○	Determine the number of days where the temperature in New York was above 30°C.
○	For Los Angeles, find the longest streak of days where the temperature was continuously below 20°C.
4.	Comparison Between Cities:
○	Compare the average temperatures of Chicago and Houston to determine which city had a warmer year on average.
○	Calculate the correlation coefficient between the temperatures of Phoenix and Los Angeles.
5.	Monthly Analysis:
○	Assuming the data starts from January 1st, calculate the average temperature for each month for New York. (Hint: You can assume each month has a fixed number of days for simplicity: January - 31, February - 28, March - 31, April - 30, May - 31, June - 30, July - 31, August - 31, September - 30, October - 31, November - 30, December - 31).
○	Identify the month with the highest average temperature for Phoenix.
Bonus Tasks:
●	Create a function to normalize the temperature data (i.e., scale the data such that the temperatures for each city have a mean of 0 and a standard deviation of 1).
●	Write a function to interpolate missing data points in the dataset (if any are present). Assume that missing data points are represented by NaN values.


In [66]:
# Temperature variability

standard_deviations_of_city=  np.std(ds_temp, axis=0)
print(standard_deviations_of_city)


temperature_range_per_day = np.ptp(ds_temp, axis=1)
print(type(temperature_range_per_day))
print(np.ndim(temperature_range_per_day))

day_with_highest_variability = np.argmax(temperature_range_per_day)
print(day_with_highest_variability)





[14.65843551 14.46341305 14.01095623 14.49873627 14.40736348]
<class 'numpy.ndarray'>
1
46


In [68]:
# Above 30 degree celcius

ny_temperatures = ds_temp[:, 0]

days_above_30c_ny = np.sum(ny_temperatures > 30)

print(days_above_30c_ny)


144


In [88]:
la_data = ds_temp[:, 1]

print(la_data)
count = 0
prev = 0
maxc = count
for data in la_data:
    if data < 20 :
    
        count += 1
        maxc = max(maxc, count)
        
    else:
        count = 0   
    
    
    

print(maxc)

[43 40 40 41 24 11  7 45 45 27  4 35  7 28 30 36 38 34 12 25 42 24 14  6
 49  7 45 10 33 42 49 42 31 18 47 29 33 25 41  0 47  1 25  6 28 48 49 45
 43  4 13 11 19  0 37 44  7 16 47 46 25 13 12 41 35  4 42 33  0 20 29 39
 23 48 14  2 13 17  2 11  6 11 44 24 42  6 27 29 12 45 35  7 21 36 18  0
 35 43 38 31 34 34  7 42 31 37 46  5 37 23 16  7  4 25 40 33 21 16 29 48
 47 16 17 19 32  8  6  5 38 14 27  2 17 24  2 17 38 22 36 17  1 17 35 34
 27 11 14 23 12 26 37 11 30  5 39 23 40 29 13 39 38 43 42 32 25  3 15 37
 41  2  8 34  5 49 42 33 31 21 48 26 42  6  8  9 35 18  4 39 26 48 12  9
 41  9 24 39 42 32 41 23  1 45 19 26 23  7 49  4 47 16 38  4 11  4 17  7
 24 11 18  2 32 14 17 31 21 43  1 43 48  6 34 26 39 34 23  2 30  9 24 40
  4 16 39 39  2 43 17 35  8  9 25 43 34 32  1 33 45 28 43 46  7 21 25 21
 12 27 34 35 45 40 42  4 28 15 14 15 32 33 21 13 36  9 12  1 28 29 29  4
 10 26 42  8  3 32 30 12  1  2  5  0  0 47 42 20 10  5 26 24  1 16 45 37
 37 32 42 20  6 49  9  8  2 24 45 47 16 24 18 18 12

In [89]:
# Chicago temperatures are in the third column (index 2)
chi_temperatures = ds_temp[:, 2]

# Houston temperatures are in the fourth column (index 3)
hou_temperatures = ds_temp[:, 3]

# Calculate average temperatures
avg_temp_chi = np.mean(chi_temperatures)
avg_temp_hou = np.mean(hou_temperatures)

print("\nComparison of average temperatures:")
print(f"Average temperature in Chicago: {avg_temp_chi}")
print(f"Average temperature in Houston: {avg_temp_hou}")

if avg_temp_chi > avg_temp_hou:
    print("Chicago had a warmer year on average.")
elif avg_temp_hou > avg_temp_chi:
    print("Houston had a warmer year on average.")
else:
    print("Chicago and Houston had the same average temperature.")



Comparison of average temperatures:
Average temperature in Chicago: 24.09041095890411
Average temperature in Houston: 24.13972602739726
Houston had a warmer year on average.


In [91]:
# Phoenix temperatures are in the fifth column (index 4)
phx_temperatures = ds_temp[:, 4]

# Calculate correlation coefficient between Phoenix and Los Angeles temperatures
corr_coef = np.corrcoef(phx_temperatures, la_data)[0, 1]
print(f"\nCorrelation coefficient between Phoenix and Los Angeles temperatures: {corr_coef}")



Correlation coefficient between Phoenix and Los Angeles temperatures: -0.11609149642662721


In [103]:

days_per_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

monthly_temps_ny = np.zeros(12)
monthly_temps_phx = np.zeros(12)

start_day = 0
for month in range(12):
    end_day = start_day + days_per_month[month]
    
    temps_ny = ds_temp[start_day:end_day, 0]  
    temps_phx = ds_temp[start_day:end_day, 4] 
    
    monthly_temps_ny[month] = np.mean(temps_ny)
    monthly_temps_phx[month] = np.mean(temps_phx)
    
    start_day = end_day

print("Average temperature for each month in New York:")
for month in range(12):
    print(f"Month {month+1}: {monthly_temps_ny[month]}")

hottest_month_phx = np.argmax(monthly_temps_phx)
print(f"\nMonth with highest average temperature in Phoenix: {hottest_month_phx + 1}")  


Average temperature for each month in New York:
Month 1: 23.096774193548388
Month 2: 22.821428571428573
Month 3: 27.225806451612904
Month 4: 24.2
Month 5: 29.161290322580644
Month 6: 22.5
Month 7: 25.612903225806452
Month 8: 26.161290322580644
Month 9: 20.133333333333333
Month 10: 25.903225806451612
Month 11: 27.766666666666666
Month 12: 26.483870967741936

Month with highest average temperature in Phoenix: 8
